# Generated by Django 2.0.4 on 2018-05-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockPrediction', '0002_auto_20180515_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_pred',
            name='down',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='stock_pred',
            name='pred',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='user_follow',
            name='sale_price',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='user_follow',
            unique_together={('code', 'username', 'buy_date')},
        ),
    ]
