# Generated by Django 2.0.4 on 2018-05-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockPrediction', '0004_auto_20180516_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_pred',
            name='macdh',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='stock_pred',
            name='mfi',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='stock_pred',
            name='rsi',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='stock_pred',
            name='stoD',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='stock_pred',
            name='stoK',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='stock_pred',
            name='ultosc',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='stock_pred',
            name='willR',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
    ]
