# Generated by Django 2.0.4 on 2018-05-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockPrediction', '0005_auto_20180516_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_pred',
            name='close',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stock_pred',
            name='high',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stock_pred',
            name='low',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stock_pred',
            name='open',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stock_pred',
            name='volume',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
    ]
