# Generated by Django 2.0.4 on 2018-05-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockPrediction', '0006_auto_20180516_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_pred',
            name='stockname',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
