# Generated by Django 2.0.4 on 2018-05-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockPrediction', '0008_auto_20180516_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='pred_anal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('stockname', models.CharField(max_length=6, null=True)),
                ('hopeopen', models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ('hopesale', models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ('buydate', models.DateField()),
                ('high', models.DecimalField(decimal_places=15, max_digits=20, null=True)),
                ('highdate', models.DateField()),
            ],
        ),
    ]
