# Generated by Django 2.0.4 on 2018-05-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockPrediction', '0009_pred_anal'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pred_anal',
            unique_together={('code', 'buydate')},
        ),
    ]
