# Generated by Django 2.0.4 on 2018-05-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockPrediction', '0010_auto_20180523_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='pred_anal',
            name='chg',
            field=models.DecimalField(decimal_places=15, max_digits=20, null=True),
        ),
    ]
